services:
  bodil-power-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data: