services:
  bodil-power-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - '27017:27017'
    volumes:
      - ./mongodata:/data/db

volumes:
  mongodata: