[package]
name = "data-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
dotenvy = "0.15.7"
mongodb = "3.0.1"
rumqttc = "0.24.0"
serde_json = "1.0.122"
tokio = "1.39.2"
