[package]
name = "data-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
dotenv = "0.15.0"
mongodb = "3.0.1"
rumqttc = "0.24.0"
serde_json = "1.0.122"
tokio = "1.39.2"
